### ISSUE TITLE
Remove connotation of lesson, unit, module from the schema 

### ISSUE THREAD

**Issue by michael-collins** [open-curriculum/oerschema#1]
We are still referencing lesson, unit, and module in the oerschema yml: https://github.com/open-curriculum/oerschema/blob/master/_src/config/schema.yml 

@curiosity26 Can we reiterate why what terminology we are using to replace module, lesson, and unit, and the rationale? I think we discussed **Collection**,  **Learning sequence** and **Learning component.** If I recall, you've decided against collection, but are keeping the other two.

**Comment by michael-collins** [comment]
related to issue #2

**Comment by curiosity26** [comment]
Because people use those terms. They are familiar with them. Collection isn't specific to learning and we're already using Learning Component, which can be a sequence or not. A Lesson, Module or Unit is a Learning Component and will allow those who wish to use them for specificity purposes to do so. You could just use Learning Component if you wish to be more generic.
