### ISSUE TITLE
licensing considerations

### ISSUE THREAD

**Issue by michael-collins** [open-curriculum/oerschema#10]
How can we denote that content is copyrighted? I guess technically, it is implied that it is copyrighted by not adding a license in the US. I'll be using some (C) material under fair use where I'll make quotations verbatim, so it would be good to indicate this. I'm going to stay away from Teach Act stuff since you can't teach with it unless there is authentication in place. This is super not fun.

**Comment by curiosity26** [comment]
If the Resource extends http://schema.org/CreativeWork, then you could use the [copyrightYear](http://schema.org/copyrightYear) and [copyrightHolder](http://schema.org/copyrightHolder) properties from Schema.org. Otherwise, the [dateCopyrighted](http://purl.org/dc/terms/dateCopyrighted) property, using [creator](http://purl.org/dc/terms/creator) property as the copyright holder, in the Dublic Core vocabulary would be applicable to all Resources.

If that's all too messy, we could just stick copyright properties on the Resource object.

**Comment by curiosity26** [comment]
I should probably mention that Dublic Core (DC) and Friend-of-a-Friend (foaf) vocabularies play nice with all RDF vocabularies. You can associate their properties with almost any RDF Class, which is what we base our Resource and all other types off of. So OER Schema gets the benefit of being compatible with many of the exiting vocabularies already in existence.

**Comment by michael-collins** [comment]
Oh good. Yeah, seems like everything is there to make this happen.

**Comment by curiosity26** [comment]
So should we just leave it up to the existing vocabs and not worry about including it?

**Comment by michael-collins** [comment]
Not sure why we'd need to reinvent the wheel on this. As long as it "works," we can focus on the pedagogy aspects with oer schema.
