### ISSUE TITLE
Aligning oerschema Course with schema.org Course

### ISSUE THREAD

**Issue by philbarker** [open-curriculum/oerschema#30]
schema.org has [Course](https://schema.org/Course) and [CourseInstance](https://schema.org/CourseInstance) types that seem a good match for oerschema's Course and CourseSection

Proposal: for better alignment with schema.org, redefine oerschema Course and CourseSection as being the same as schema.org Course and CourseInstance.

This will entail 
- [ ] resolving those properties of the current oerschema types can be replaced / declared to be the same as existing schema.org properties e.g. 
-  - [ ] http://oerschema.org/prerequisite/ and https://schema.org/coursePrerequisites are the same
-  - [ ]  I think http://oerschema.org/duration/ is intended to be the same as https://schema.org/timeRequired
-  - [ ] are oerschema hasChild childOf, & hasComponent componentOf different to schema.org hasPart partOf ? 
- - [ ] ...?
- [ ] resolving where the modeling in oerschema and schema.org differ 
- - [ ] in schema.org a Course doesn't have an instructor, it has an author and different CourseInstances may have different instructors; 
- - [ ] schema.org courses apply to sequences of any length, so there is no distinction between Course/Unit/Module.
- - [ ] ...?

**Comment by kat-wehr** [comment]
Hi! I'm going to jump in here, since I haven't been able to make it to the synchronous meetings yet and Mike asked me to take a look. Getting to one is on my to-do list - I just need to wait for a time that doesn't conflict with my class schedule! :) 

>     http://oerschema.org/prerequisite/ and https://schema.org/coursePrerequisites are the same

>    I think http://oerschema.org/duration/ is intended to be the same as https://schema.org/timeRequired

>    are oerschema hasChild childOf, & hasComponent componentOf different to schema.org hasPart partOf ?

Yes, yes and no. So, I believe these can be easily combined without much drama. 

> in schema.org a Course doesn't have an instructor, it has an author and different CourseInstances may have different instructors;

This makes sense to me and I think it works. 

> schema.org courses apply to sequences of any length, so there is no distinction between Course/Unit/Module

@michael-collins and I discussed this at length. I fall on the side of believing this is important to distinguish. We discussed unit/module (the terms themselves are interchangeable as far as I'm concerned) as parts of a course, with their own goals and objectives that are derivatives of the overall course goals and objectives. For instance, a full course (by our definition) can be broken down into component parts. Those parts might be individual concepts or skills that build on one another and lead participants closer to achieving the overall course goals. Considering potential for remixing, I think it's important to distinguish that a certain chunk of content is part of a larger whole. That way if I wanted to swap out a Unit 2 for similar content from another source, I could easily look for another collection of content with goals and objectives similar to the ones from my original Unit 2.

Of course, a full course could also NOT have any units/modules. From my professional experience, it's way more common for a course to be broken up in parts. I wonder though if something like "topic" might be better suited to fill this role? Continuing with my example, if I were to search for remixable content, I'd be looking for something based on topic, not another "unit 2..." 

Is there a comparable property that fits this in schema.org's definitions?

**Comment by philbarker** [comment]
Thanks @kat-wehr , that's really useful & good to know that we agree on so much.

On Courses. I think that the division of a long course into segments is useful, and absolutely should be kept. For us on OCX it is a key feature for what we want to convey. So I wasn't thinking of flattening it out of OERSchema to match schema.org:Course. At the same time, it would be problematic to put it into schema.org because of the mismatches in language that there are around program/course/module
[Aside: in the UK, in some Universities a student will be studying a 4 year programme in their subject which is divided in courses, e.g. a 4yr programme on Computer Science with courses on programming, human factors, user experience etc.; but most Universities they will be on a 4 yr *course* which is divided into modules. See also my q about what is the definition of oerschema:Program #31)]

What I am thinking is that oerschema's Module and Unit may be subtypes of schema.org Course. I am not sure whether oerschema:Course is the same as schema.org:Course, I think that logically it is a subtype because not all schema:Courses are oer:Courses. What do you think?

I'm not sure where Topic fits in with this. I think I need to add it to the terms that I don't understand from their definition :)

**Comment by michael-collins** [comment]
@philbarker, @kat-wehr and I had some time to sit down and talk through these questions. We didn't get through all of them, but we looked at a few of the points you raised. We are leaning towards the idea that a module and unit is in fact a subtype of course. We are also looking at a broader definition for course that could help with the word usage differences. We'll do a pull request with some changes and ask you to review.

**Comment by philbarker** [comment]
I think it would be good to talk about this before a pull request. I have a few more questions, and some new perspectives to suggest. Any chance of a time to chat next week?

⁣Get TypeApp for Android ​

**Comment by michael-collins** [comment]
@philbarker Sounds good, will send you an email to coordinate.

**Comment by michael-collins** [comment]
@philbarker We are ramping up again in early May to build the schema into HAX. Do you recall where we landed on this per our last conversation?

**Comment by philbarker** [comment]
@michael-collins I am not sure where we got to, but since we had this conversation schema.org have introduced a type for "program" https://schema.org/EducationalOccupationalProgram which (confusingly) might be better match to oerschema:Course than schema.org:Course is (with schema.org:Course mapping to oerschema:Module). 

Happy to re-open this conversation / start afresh

**Comment by michael-collins** [comment]
@philbarker That would be great. Zoom call or conversation in this thread?

**Comment by philbarker** [comment]
Zoom call might be the best way to refocus, if you have time.  I have good availability next week in my afternoons / your mornings.

**Comment by michael-collins** [comment]
Action items:

[ ] import schema.org course and ensure related oerschema vocabulary work properly.
[ ] import https://schema.org/timeRequired to replace http://oerschema.org/duration/
[ ] import https://schema.org/coursePrerequisites to replace http://oerschema.org/prerequisite/
[ ] Add: "author" to course
[ ] Question for Alex: course is relatively the same as units and modules (should we make schema.org properties available to module and units) what needs to be removed and what can be replaced with https://schema.org/Course
[ ] Question for Alex: oerschema hasChild childOf, & hasComponent componentOf different to schema.org hasPart partOf ?
